apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: microshop
data:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/products"
  OTEL_SERVICE_NAME: "product-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector:4318"
  OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
  OTEL_TRACES_SAMPLER_ARG: "1.0"
  REDIS_URL: "redis://redis:6379"
