apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: microshop
data:
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/payments"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
  PAYMENT_FAILURE_RATE: "0.3"
  OTEL_SERVICE_NAME: "payment-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector:4318"
  OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
  OTEL_TRACES_SAMPLER_ARG: "1.0"
