apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: microshop
data:
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
  SMTP_HOST: ""
  SMTP_PORT: "587"
  OTEL_SERVICE_NAME: "notification-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector:4318"
  OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
  OTEL_TRACES_SAMPLER_ARG: "1.0"
