apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: microshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: microshop/notification-service:latest
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: notification-service-config
            - secretRef:
                name: microshop-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
