apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: microshop
data:
  init.sql: |
    CREATE DATABASE auth;
    CREATE DATABASE products;
    CREATE DATABASE orders;
    CREATE DATABASE inventory;
    CREATE DATABASE payments;
