apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: microshop
data:
  PROXY_TARGET_AUTH: "http://auth-service:3006"
  PROXY_TARGET_PRODUCTS: "http://product-service:3001"
  PROXY_TARGET_ORDERS: "http://order-service:3002"
  PROXY_TARGET_INVENTORY: "http://inventory-service:3003"
  PROXY_TARGET_PAYMENT: "http://payment-service:3004"
  PROXY_TARGET_NOTIFICATION: "http://notification-service:3005"
  OTEL_SERVICE_NAME: "api-gateway"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector:4318"
  OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
  OTEL_TRACES_SAMPLER_ARG: "1.0"
