FROM oven/bun:1-alpine
RUN apk add --no-cache openssl
WORKDIR /app
COPY package.json ./
RUN bun install
COPY prisma/ ./prisma/
RUN bunx prisma generate
COPY src/ ./src/
EXPOSE 3002
CMD ["bun", "run", "src/index.ts"]
